# This script is generated by a local LLM and I only checked the output files

import os
import re
import sys
import argparse
from PIL import Image


def compute_pixel_intensity(row, col, total_rows, black_band_lines, fade_lines):
    center = total_rows // 2
    half_band = black_band_lines // 2
    dist_from_center = abs(row - center)

    if dist_from_center < half_band:
        return 0.0
    elif dist_from_center < half_band + fade_lines:
        fade_pos = (dist_from_center - half_band + 1) / fade_lines
        return fade_pos
    else:
        return 1.0


# 4x4 Bayer threshold matrix for ordered dithering
# Values 0-15, normalized to 0.0-1.0 range (threshold = value/16)
BAYER_4x4 = [
    [0, 8, 2, 10],
    [12, 4, 14, 6],
    [3, 11, 1, 9],
    [15, 7, 13, 5],
]


def apply_ordered_dithering(intensity_grid, width, height, center):
    """Ordered dithering using 4x4 Bayer matrix, threshold normalized to 0-1."""
    result = [[0 for _ in range(width)] for _ in range(height)]
    for row in range(height):
        for col in range(width):
            intensity = intensity_grid[row][col]
            if intensity <= 0.0:
                result[row][col] = 0
            elif intensity >= 1.0:
                result[row][col] = 255
            else:
                # Mirror row around center for vertical symmetry
                mirrored_row = center - abs(row - center)
                threshold = BAYER_4x4[mirrored_row % 4][col % 4] / 16.0
                result[row][col] = 255 if intensity > threshold else 0
    return result


def generate_i1(
    width,
    height,
    black_band_lines,
    fade_lines,
    output_path,
    png_path,
    name,
    tri_period=16,
    tri_height=4,
):
    center = height // 2

    # Compute uniform intensity grid first
    intensity_grid = []
    for row in range(height):
        row_data = []
        for col in range(width):
            intensity = compute_pixel_intensity(
                row, col, height, black_band_lines, fade_lines
            )
            row_data.append(intensity)
        intensity_grid.append(row_data)

    # Triangular wave: 0 -> tri_height -> 0 over tri_period columns
    def tri_shift(col):
        phase = (col % tri_period) / tri_period
        if phase < 0.5:
            return int(phase * 2 * tri_height)
        else:
            return int((1 - phase) * 2 * tri_height)

    # Shift each column outward from center by the triangular wave amount
    for col in range(width):
        s = tri_shift(col)
        if s > 0:
            above = [intensity_grid[r][col] for r in range(center)]
            below = [intensity_grid[r][col] for r in range(center, height)]
            shifted_above = above[s:] + [0.0] * s
            shifted_below = [0.0] * s + below[:-s]
            for r in range(center):
                intensity_grid[r][col] = shifted_above[r]
            for r in range(center, height):
                intensity_grid[r][col] = shifted_below[r - center]

    # Ordered dither the shifted grid
    dithered = apply_ordered_dithering(intensity_grid, width, height, center)

    # Pack into I1 bitstream: 0 = black, 1 = white
    pixels = []
    png_pixels = []
    for row in range(height):
        byte_val = 0
        for col in range(width):
            luminance = dithered[row][col]
            bit = 1 if luminance == 255 else 0
            # MSB first per row
            byte_val = (byte_val << 1) | bit
            if (col + 1) % 8 == 0 or col == width - 1:
                # Pad last byte of row if needed
                padded = (
                    byte_val << (8 - ((col + 1) % 8))
                    if col == width - 1 and (col + 1) % 8 != 0
                    else byte_val
                )
                pixels.append(padded)
                byte_val = 0
            png_pixels.append(luminance)

    # Write C file in LVGL I1 format
    stride = (width + 7) // 8  # bytes per row for I1
    with open(output_path, "w") as f:
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#define LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#endif\n\n")
        f.write(f"#ifndef LV_ATTRIBUTE_{name.upper()}\n")
        f.write(f"#define LV_ATTRIBUTE_{name.upper()}\n")
        f.write("#endif\n\n")
        f.write(
            f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_{name.upper()}\n"
        )
        f.write(f"    uint8_t {name}_map[] = {{\n")
        f.write("        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/\n")
        f.write("        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/\n")

        bytes_per_line = 12
        for i in range(0, len(pixels), bytes_per_line):
            chunk = pixels[i : i + bytes_per_line]
            hex_strs = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"        {hex_strs},\n")

        f.write("};\n\n")
        f.write(f"const lv_image_dsc_t {name} = {{\n")
        f.write("    .header =\n")
        f.write("        {\n")
        f.write("            .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("            .cf = LV_COLOR_FORMAT_I1,\n")
        f.write("            .flags = 0,\n")
        f.write(f"            .w = {width},\n")
        f.write(f"            .h = {height},\n")
        f.write(f"            .stride = {stride},\n")
        f.write("            .reserved_2 = 0,\n")
        f.write("        },\n")
        f.write(f"    .data_size = sizeof({name}_map),\n")
        f.write(f"    .data = {name}_map,\n")
        f.write("    .reserved = NULL,\n")
        f.write("};\n")

    # Write PNG for inspection
    img = Image.new("L", (width, height))
    img.putdata(png_pixels)
    img.save(png_path)

    file_size = len(pixels)
    print(f"Generated {output_path} ({file_size} bytes) and {png_path}")


def generate_al88(
    width,
    height,
    black_band_lines,
    fade_lines,
    output_path,
    png_path,
    name,
    tri_period=16,
    tri_height=4,
):
    center = height // 2

    # Compute uniform intensity grid first
    intensity_grid = []
    for row in range(height):
        row_data = []
        for col in range(width):
            intensity = compute_pixel_intensity(
                row, col, height, black_band_lines, fade_lines
            )
            row_data.append(intensity)
        intensity_grid.append(row_data)

    # Triangular wave: 0 -> tri_height -> 0 over tri_period columns
    def tri_shift(col):
        phase = (col % tri_period) / tri_period
        if phase < 0.5:
            return int(phase * 2 * tri_height)
        else:
            return int((1 - phase) * 2 * tri_height)

    # Shift each column outward from center by the triangular wave amount
    for col in range(width):
        s = tri_shift(col)
        if s > 0:
            above = [intensity_grid[r][col] for r in range(center)]
            below = [intensity_grid[r][col] for r in range(center, height)]
            shifted_above = above[s:] + [0.0] * s
            shifted_below = [0.0] * s + below[:-s]
            for r in range(center):
                intensity_grid[r][col] = shifted_above[r]
            for r in range(center, height):
                intensity_grid[r][col] = shifted_below[r - center]

    # Ordered dither the shifted grid
    dithered = apply_ordered_dithering(intensity_grid, width, height, center)

    # Flatten to output buffers
    pixels = []
    png_pixels = []
    for row in range(height):
        for col in range(width):
            luminance = dithered[row][col]
            alpha = 0xFF
            pixels.append(alpha)
            pixels.append(luminance)
            png_pixels.append(luminance)

    # Write C file in LVGL format (matching grid.c)
    stride = width * 2  # AL88: 2 bytes per pixel
    with open(output_path, "w") as f:
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#define LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#endif\n\n")
        f.write("#ifndef LV_ATTRIBUTE_GRID\n")
        f.write("#define LV_ATTRIBUTE_GRID\n")
        f.write("#endif\n\n")
        f.write(
            f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_GRID\n"
        )
        f.write(f"    uint8_t {name}_map[] = {{\n")

        # Format 12 bytes per line, matching grid.c style
        bytes_per_line = 12
        for i in range(0, len(pixels), bytes_per_line):
            chunk = pixels[i : i + bytes_per_line]
            hex_strs = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"        {hex_strs},\n")

        f.write("};\n\n")
        f.write(f"const lv_image_dsc_t {name} = {{\n")
        f.write("    .header =\n")
        f.write("        {\n")
        f.write("            .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("            .cf = LV_COLOR_FORMAT_AL88,\n")
        f.write("            .flags = 0,\n")
        f.write(f"            .w = {width},\n")
        f.write(f"            .h = {height},\n")
        f.write(f"            .stride = {stride},\n")
        f.write("            .reserved_2 = 0,\n")
        f.write("        },\n")
        f.write(f"    .data_size = sizeof({name}_map),\n")
        f.write(f"    .data = {name}_map,\n")
        f.write("    .reserved = NULL,\n")
        f.write("};\n")

    # Write PNG for inspection
    img = Image.new("L", (width, height))
    img.putdata(png_pixels)
    img.save(png_path)

    file_size = len(pixels)
    print(f"Generated {output_path} ({file_size} bytes) and {png_path}")


def parse_c_array(filepath):
    """Extract byte values from a C array definition."""
    with open(filepath) as f:
        content = f.read()

    match = re.search(r"(?:_map\[\]|=)\s*\{([^}]+)\}", content, re.DOTALL)
    if not match:
        print(f"Could not find map array in {filepath}")
        sys.exit(1)

    hex_values = re.findall(r"0x([0-9a-fA-F]{2})", match.group(1))
    return bytes(int(v, 16) for v in hex_values)


def parse_image_descriptor(filepath):
    """Extract width, height, stride from the image descriptor."""
    with open(filepath) as f:
        content = f.read()

    w_match = re.search(r"\.w\s*=\s*(\d+)", content)
    h_match = re.search(r"\.h\s*=\s*(\d+)", content)
    stride_match = re.search(r"\.stride\s*=\s*(\d+)", content)

    if not all([w_match, h_match, stride_match]):
        print(f"Could not parse image descriptor in {filepath}")
        sys.exit(1)

    return int(w_match.group(1)), int(h_match.group(1)), int(stride_match.group(1))


def al88_to_i1(data, width, height, stride):
    """Convert AL88 pixel data to I1 bitstream.

    AL88: each pixel is 2 bytes [alpha, luminance]
    I1:   each pixel is 1 bit (luminance > 0 -> 1, else 0), MSB first per row
    """
    i1_bytes = bytearray()
    for row in range(height):
        row_offset = row * stride
        col = 0
        while col < width:
            byte_val = 0
            for bit_pos in range(7, -1, -1):
                if col >= width:
                    break
                pixel_offset = row_offset + col * 2
                luminance = data[pixel_offset + 1]
                byte_val |= (1 if luminance > 0 else 0) << bit_pos
                col += 1
            i1_bytes.append(byte_val)
    return bytes(i1_bytes)


def convert_file(filepath):
    """Convert a single AL88 .c file to I1 format in-place."""
    name = os.path.splitext(os.path.basename(filepath))[0]

    print(f"Processing {name}...")

    width, height, stride = parse_image_descriptor(filepath)
    data = parse_c_array(filepath)

    expected_size = stride * height
    if len(data) != expected_size:
        print(f"  Warning: data size {len(data)} != expected {expected_size}")

    bad_alpha = sum(1 for i in range(0, len(data), 2) if data[i] != 0xFF)
    if bad_alpha:
        print(f"  Warning: {bad_alpha} pixels have alpha != 0xFF")

    bad_lum = sum(1 for i in range(1, len(data), 2) if data[i] not in (0x00, 0xFF))
    if bad_lum:
        print(f"  Warning: {bad_lum} pixels have luminance not 0x00 or 0xFF")

    i1_data = al88_to_i1(data, width, height, stride)
    i1_stride = (width + 7) // 8

    old_size = len(data)
    new_size = 8 + len(i1_data)
    savings = old_size - new_size
    pct = 100 * savings / old_size if old_size else 0

    with open(filepath, "w") as f:
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#define LV_ATTRIBUTE_MEM_ALIGN\n")
        f.write("#endif\n\n")
        f.write(f"#ifndef LV_ATTRIBUTE_{name.upper()}\n")
        f.write(f"#define LV_ATTRIBUTE_{name.upper()}\n")
        f.write("#endif\n\n")
        f.write(
            f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_{name.upper()}\n"
        )
        f.write(f"    uint8_t {name}_map[] = {{\n")
        f.write("        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/\n")
        f.write("        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/\n")

        bytes_per_line = 12
        for i in range(0, len(i1_data), bytes_per_line):
            chunk = i1_data[i : i + bytes_per_line]
            hex_strs = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"        {hex_strs},\n")

        f.write("};\n\n")
        f.write(f"const lv_image_dsc_t {name} = {{\n")
        f.write("    .header =\n")
        f.write("        {\n")
        f.write("            .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("            .cf = LV_COLOR_FORMAT_I1,\n")
        f.write("            .flags = 0,\n")
        f.write(f"            .w = {width},\n")
        f.write(f"            .h = {height},\n")
        f.write(f"            .stride = {i1_stride},\n")
        f.write("            .reserved_2 = 0,\n")
        f.write("        },\n")
        f.write(f"    .data_size = sizeof({name}_map),\n")
        f.write(f"    .data = {name}_map,\n")
        f.write("    .reserved = NULL,\n")
        f.write("};\n")

    print(
        f"  {old_size} -> {new_size} bytes (saved {savings} bytes, {pct:.0f}% reduction)"
    )
    return savings


def add_palette_to_i1(filepath):
    """Add color palette to an I1 image that's missing it."""
    with open(filepath) as f:
        content = f.read()

    if "Color of index 0" in content:
        print(f"  {os.path.basename(filepath)}: already has palette, skipping")
        return

    name = os.path.splitext(os.path.basename(filepath))[0]

    old_start = f"uint8_t {name}_map[] = {{\n"
    new_start = f"uint8_t {name}_map[] = {{\n        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/\n        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/\n"

    if old_start not in content:
        print(f"  {os.path.basename(filepath)}: could not find map array start")
        return

    content = content.replace(old_start, new_start)

    with open(filepath, "w") as f:
        f.write(content)

    print(f"  {os.path.basename(filepath)}: palette added")


def main():
    parser = argparse.ArgumentParser(
        description="Generate LVGL images or convert AL88 to I1"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # --- generate subcommand ---
    gen = subparsers.add_parser("generate", help="Generate a new image")
    gen.add_argument(
        "--width", type=int, default=160, help="Image width in pixels (default: 160)"
    )
    gen.add_argument(
        "--height", type=int, default=68, help="Image height in pixels (default: 68)"
    )
    gen.add_argument(
        "--black-band",
        type=int,
        default=30,
        help="Number of solid black lines at center (default: 30)",
    )
    gen.add_argument(
        "--fade-lines",
        type=int,
        default=8,
        help="Number of dithered fade lines per side (default: 8)",
    )
    gen.add_argument(
        "--output",
        "-o",
        type=str,
        default="output.c",
        help="C output file path (default: output.c)",
    )
    gen.add_argument(
        "--png",
        "-p",
        type=str,
        default="output.png",
        help="PNG output file path for inspection (default: output.png)",
    )
    gen.add_argument(
        "--name",
        "-n",
        type=str,
        default="center_frame",
        help="Name for the LVGL image descriptor (default: center_frame)",
    )
    gen.add_argument(
        "--tri-period",
        "-t",
        type=int,
        default=8,
        help="Triangular wave period in columns (default: 16)",
    )
    gen.add_argument(
        "--tri-height",
        "-H",
        type=int,
        default=2,
        help="Max outward shift in rows for triangular wave (default: 4)",
    )
    gen.add_argument(
        "--i1", action="store_true", help="Output I1 (1-bit monochrome) instead of AL88"
    )

    # --- convert subcommand ---
    conv = subparsers.add_parser("convert", help="Convert AL88 .c files to I1 in-place")
    conv.add_argument("files", nargs="+", help="AL88 .c files to convert")

    # --- palette subcommand ---
    pal = subparsers.add_parser(
        "palette", help="Add I1 color palette to images missing it"
    )
    pal.add_argument("files", nargs="+", help="I1 .c files to add palette to")

    args = parser.parse_args()

    if args.command == "generate":
        if args.black_band + 2 * args.fade_lines > args.height:
            print("Error: black_band + 2*fade_lines exceeds image height")
            sys.exit(1)
        gen_func = generate_i1 if args.i1 else generate_al88
        gen_func(
            args.width,
            args.height,
            args.black_band,
            args.fade_lines,
            args.output,
            args.png,
            args.name,
            args.tri_period,
            args.tri_height,
        )

    elif args.command == "convert":
        total_savings = 0
        for filepath in args.files:
            if not os.path.isfile(filepath):
                print(f"File not found: {filepath}")
                continue
            total_savings += convert_file(filepath)
        print(f"\nTotal flash savings: {total_savings} bytes")

    elif args.command == "palette":
        for filepath in args.files:
            if not os.path.isfile(filepath):
                print(f"File not found: {filepath}")
                continue
            add_palette_to_i1(filepath)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
